# Bike-Sharing Service Demand Analysis
---
adsfadsf bla bla bal

## 0. Preparation

### A. Import prerequisite libraries:

1. Numpy
2. Pandas
3. Matplotlib
4. Seaborn

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

### B. Load the dataset

In [ ]:
df = pd.read_csv('dataset_bikesharing.csv')

In [ ]:
df

,date,season,year,month,hour,is_holiday,weekday,is_workingday,weathersit,temp,norm_temp,atemp,norm_atemp,hum,norm_hum,windspeed,norm_windspeed,n_casual_order,n_registered_order,total_order
0,2011-01-01,Spring,2011,1,0,0,Saturday,0,1,9.84,0.24,14.395,0.2879,81,0.81,0.0000,0.0000,3,13,16
1,2011-01-01,Spring,2011,1,1,0,Saturday,0,1,9.02,0.22,13.635,0.2727,80,0.80,0.0000,0.0000,8,32,40
2,2011-01-01,Spring,2011,1,2,0,Saturday,0,1,9.02,0.22,13.635,0.2727,80,0.80,0.0000,0.0000,5,27,32
3,2011-01-01,Spring,2011,1,3,0,Saturday,0,1,9.84,0.24,14.395,0.2879,75,0.75,0.0000,0.0000,3,10,13
4,2011-01-01,Spring,2011,1,4,0,Saturday,0,1,9.84,0.24,14.395,0.2879,75,0.75,0.0000,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,Spring,2012,12,19,0,Monday,1,2,10.66,0.26,12.880,0.2576,60,0.60,11.0014,0.1642,11,108,119
17375,2012-12-31,Spring,2012,12,20,0,Monday,1,2,10.66,0.26,12.880,0.2576,60,0.60,11.0014,0.1642,8,81,89
17376,2012-12-31,Spring,2012,12,21,0,Monday,1,1,10.66,0.26,12.880,0.2576,60,0.60,11.0014,0.1642,7,83,90
17377,2012-12-31,Spring,2012,12,22,0,Monday,1,1,10.66,0.26,13.635,0.2727,56,0.56,8.9981,0.1343,13,48,61
17378,2012-12-31,Spring,2012,12,23,0,Monday,1,1,10.66,0.26,13.635,0.2727,65,0.65,8.9981,0.1343,12,37,49

## 1. Descriptive Analysis

### A. Calculate the **mean** of the hourly number of order(s)

In [ ]:
avg_n_order = df['total_order'].mean()
print(f'MEAN of the hourly number of order: {avg_n_order}')

MEAN of the hourly number of order: 189.46308763450142

### B. Calculate the **median** of the hourly number of order(s)

In [ ]:
mid_n_order = df['total_order'].median()
print(f'MEDIAN of hourly number of order: {mid_n_order}')

MEDIAN of hourly number of order: 142.0

### C. Calculate the **mode** of the hourly number of order(s)

In [ ]:
mode_n_order = df['total_order'].mode()
print(f'MODE of hourly number of order: {mode_n_order}')

MODE of hourly number of order: 0    5
dtype: int64

## 2. Discrete Variable Analysis

## 3. Continuous Variable Analysis

## 4. Correlation Analysisa

## 5. Hypothesis Testing